# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='patrocinador',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
