# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('tipo_campeonato', models.CharField(choices=[('Q', 'Quadra'), ('C', 'Campo')], default='Q', max_length=1)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=False)),
                ('campeonato_principal', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'campeonato',
            },
        ),
    ]
