# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('data_fundacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('nome',),
                'db_table': 'clube',
            },
        ),
    ]
